# Generated by Django 5.1.2 on 2024-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scene_saver", "0002_alter_scanesaverinfo_save_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanesaverinfo",
            name="save_time",
            field=models.TextField(),
        ),
    ]
